#pragma once

#include "app.h"

typedef enum
{
    NFC_COMMAND_INVALID = 0U,
    NFC_COMMAND_INVENTORY,
    NFC_COMMAND_READ_SINGLE_BLOCK,
    NFC_COMMAND_WRITE_SINGLE_BLOCK,
    NFC_COMMAND_READ_MULTIPLE_BLOCK,
    NFC_COMMAND_FAST_READ_SINGLE_BLOCK,
    NFC_COMMAND_FAST_READ_MULTIPLE_BLOCK,
    NFC_COMMAND_GET_SYS_INFO,
} NFCCommand;

#if FTR_NFCTAG

#endif